// API action types
export const GET_TRACKS = 'GET_TRACKS';
export const GET_TRACKS_PENDING = 'GET_TRACKS_PENDING';
export const GET_TRACKS_FULFILLED = 'GET_TRACKS_FULFILLED';

// Browse action types
export const SET_GENRE = 'SET_GENRE';

// Player action types
export const PLAYER_AUDIO_LOADING_REQUEST = 'PLAYER_AUDIO_LOADING_REQUEST';
export const PLAYER_AUDIO_LOADING_SUCCESS = 'PLAYER_AUDIO_LOADING_SUCCESS';
export const PLAYER_AUDIO_LOADING_FAILURE = 'PLAYER_AUDIO_LOADING_FAILURE';

export const PLAYER_SET_IS_PLAYING = 'PLAYER_SET_IS_PLAYING';
export const PLAYER_SET_CURRENT_TRACK = 'PLAYER_SET_CURRENT_TRACK';
export const PLAYER_SET_NOW_PLAYING = 'PLAYER_SET_NOW_PLAYING';
export const PLAYER_ADD_TO_QUEUE = 'PLAYER_ADD_TO_QUEUE';

export const PLAYER_NEXT_TRACK = 'PLAYER_NEXT_TRACK';
